package controller;

/**
 * This exception is thrown when searching for a {@code User} {@code id} that does not exist.
 * @author Pietro Dellino
 *
 */
public class InexistingUserIdException extends Exception {
	
	private int id;

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -8989193763190497737L;

	public InexistingUserIdException(int id) {
		this.id = id;
	}
	
	@Override
	public String getMessage() {
		String message = "No User with id:" + this.id;
		return message;
	}

}
