package controller;

import ride.Network;

/**
 * This exception is thrown when searching for a {@code Station }{@code id} that does not exist.
 * @author Chloé
 *
 */
public class InexistingStationIdException extends Exception {
	
	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = 7313842031546783752L;
	private int stationID;
	private Network net;

	public InexistingStationIdException(int id, Network net) {
		this.stationID = id;
		this.net = net;
	}
	
	@Override
	public String getMessage() {
		String message = "Could not find a station with id " + this.stationID + " in network " + this.net.getName() + ".";
		return message;
	}

}
