package controller;

/**
 * This exception is thrown when searching for {@code Slot id} that does not exist.
 * @author Chloé
 *
 */
public class InexistingSlotIdException extends Exception {
	
	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = 3237027055997923339L;
	private int id;
	
	public InexistingSlotIdException(int id) { this.id = id; }
	
	@Override
	public String getMessage() {
		String message = "No Slot with id:" + this.id;
		return message;
	}

}
