package controller;

/**
 * This exception is thrown when searching for a {@code Network} name that does not exist. 
 * @author Chloé
 *
 */
public class InexistingNetworkNameException extends Exception {
	
	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -7238609877747575739L;
	private String name;
	
	public InexistingNetworkNameException(String name) {
		this.name = name;
	}
	
	@Override
	public String getMessage() {
		String message = "There is no network named \"" + this.name + "\".";
		return message;
	}

}
