package card;

import java.io.ObjectStreamException;
import java.io.Serializable;

/**
 * An ID generator for the cards.
 * @author Pietro Dellino
 *
 */
public class CardIdGenerator implements Serializable {
	
	/**
	 * This serial version UID has been generated by Papyrus.
	 */
	private static final long serialVersionUID = 5011021007026164816L;
	
	private static CardIdGenerator instance = null;
	private int numCards;
	
	private CardIdGenerator() {}
	
	/**
	 * This method returns the unique instance of the class (singleton pattern).
	 */
	public static synchronized CardIdGenerator getInstance() {
		if (instance == null) { instance = new CardIdGenerator(); }
		return instance;
	}
	
	public synchronized int getNextId() { return numCards++; }
	
	/**
	 * This methods ensures that even when an {@code CardIdGenerator} is serialized, the unique instance is always returned.
	 * @return The unique instance of the class.
	 * @throws ObjectStreamException
	 */
	public Object readResolve() throws ObjectStreamException {
		return instance;
	}
	
	

}
