package station;

/**
 * This exception is thrown when a {@code User} tries to pick up a {@code Bike} from a {@code Station} that has no {@code Bike} available.
 * @author Chloé
 *
 */
public class NoBikeAvailableException extends Exception {

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = 348248456248678570L;
	
	@Override
	public String getMessage() {
		return "There is no bike available in this station. ";
	}
}
