package station;

/**
 * This exception is thrown when a {@code User} tries to pick up a {@code ElectricBike} from a {@code Station} that has no {@code ElectricBike} available.
 * @author Chloé
 *
 */
public class NoElectricBikeAvailableException extends Exception {

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -3101773794035526661L;
	
	@Override
	public String getMessage() {
		return "There is no electric bike available in this station.";
	}

}
