package station;

import java.time.LocalDateTime;

/**
 * This exception is thrown when someone tries to get the {@code SlotState} of a {@code Slot} before it was created.
 * @author Chloé
 *
 */
public class NoSlotStateAtDateException extends Exception {
	
	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = 2651831164435357865L;
	
	private LocalDateTime time;

	public NoSlotStateAtDateException(LocalDateTime time) {
		super();
		this.time = time;
	}

	public LocalDateTime getTime() {
		return time;
	}

	@Override
	public String getMessage() {
		return "There is no Slot State saved for time : [" + time + "].";
}
	
	

}