package station;

/**
 * This exception is throw when a {@code User} tries to pick up a {@code Bike} from a {@code Station} but he has an ongoing {@code Ride}, meaning he already has a {@code Bike}.
 * @author Chloé
 *
 */
public class OngoingRideException extends Exception{

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = 6334792746855489550L;
	
	@Override
	public String getMessage() {
		return "The user has a ongoing ride.";
	}

	
}
