package ui.clui;
/**
 * This exception is thrown when an invalid command is entered.
 * @author Chloé
 *
 */
public class InvalidCommandException extends Exception {
	
	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -8031042864184442175L;
	private String command;
	
	public InvalidCommandException(String com) {
		this.command = com;
	}
	
	@Override
	public String getMessage() {
		return "The command \"" + this.command + "\" is not valid.";
	}

}
